#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

#exec git update-server-info
exec ../git_hook_scripts/pull_from_remote.sh --remote=live --destination_repo=../tariffcalculator
